### ISSUE TITLE
Error: No default engine was specified and no extension was provided.

### ISSUE THREAD

**Issue by AviorAlong** [uniquejava/node_imooc#2]
在慕课网看视频做的，但是第一步就出错了，windows 7 环境下，依赖包都装在项目下，但是执行程序后，显示imooc started on 8885，但是一访问就报如下错误，请指点（由于不是全局安装，所以执行jade -V 不识别，进入jade目录，执行jade -V 没有响应，也把jade换成 pug 试过，还是同样的错误）
Error: No default engine was specified and no extension was provided.
    at new View (F:\Imooc\node_modules\express\lib\view.js:62:11)
    at EventEmitter.render (F:\Imooc\node_modules\express\lib\application.js:569:12)
    at ServerResponse.render (F:\Imooc\node_modules\express\lib\response.js:960:7)
    at F:\Imooc\app.js:13:6
    at Layer.handle [as handle_request] (F:\Imooc\node_modules\express\lib\router\layer.js:95:5)
    at next (F:\Imooc\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (F:\Imooc\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (F:\Imooc\node_modules\express\lib\router\layer.js:95:5)
    at F:\Imooc\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (F:\Imooc\node_modules\express\lib\router\index.js:330:12)
Error: No default engine was specified and no extension was provided.
    at new View (F:\Imooc\node_modules\express\lib\view.js:62:11)
    at EventEmitter.render (F:\Imooc\node_modules\express\lib\application.js:569:12)
    at ServerResponse.render (F:\Imooc\node_modules\express\lib\response.js:960:7)
    at F:\Imooc\app.js:13:6
    at Layer.handle [as handle_request] (F:\Imooc\node_modules\express\lib\router\layer.js:95:5)
    at next (F:\Imooc\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (F:\Imooc\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (F:\Imooc\node_modules\express\lib\router\layer.js:95:5)
    at F:\Imooc\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (F:\Imooc\node_modules\express\lib\router\index.js:330:12)

**Comment by uniquejava** [comment]
看不到你的代码, 你git clone我的代码试试.
